# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:
    inputs:
      azureRegion:
        description: "Azure Region"
        required: true
      resourceGroup:
        description: "Resource Group"
        required: true
      appServicePlan:
        description: "App Service Plan"
        required: false
      webAppName:
        description: "Web App Name"
        required: false

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Deploy Azure Web App Infrastructure
      uses: azure/cli@v1
      with:
        inlineScript: |
          az group create --name ${{ github.event.inputs.resourceGroup }} --location ${{ github.event.inputs.azureRegion }}
       
